

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres




spring.main.web-application-type=servlet

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

